/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			fontFamily: {
				'sans': ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
				'display': ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
				'body': ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
				'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
			},
			fontSize: {
				'xs': ['0.75rem', { lineHeight: '1rem' }],
				'sm': ['0.875rem', { lineHeight: '1.25rem' }],
				'base': ['1rem', { lineHeight: '1.5rem' }],
				'lg': ['1.125rem', { lineHeight: '1.75rem' }],
				'xl': ['1.25rem', { lineHeight: '1.75rem' }],
				'2xl': ['1.5rem', { lineHeight: '2rem' }],
				'3xl': ['1.875rem', { lineHeight: '2.25rem' }],
				'4xl': ['2.25rem', { lineHeight: '2.5rem' }],
				'5xl': ['3rem', { lineHeight: '1' }],
				'6xl': ['3.75rem', { lineHeight: '1' }],
				'7xl': ['4.5rem', { lineHeight: '1' }],
				'8xl': ['6rem', { lineHeight: '1' }],
				'9xl': ['8rem', { lineHeight: '1' }],
			},
			animation: {
				'fade-in': 'fadeIn 0.5s ease-in-out',
				'fade-up': 'fadeUp 0.5s ease-out',
				'slide-in': 'slideIn 0.3s ease-out',
				'scale-in': 'scaleIn 0.2s ease-out',
				'spin-slow': 'spin 3s linear infinite',
			},
			keyframes: {
				fadeIn: {
					'0%': { opacity: '0' },
					'100%': { opacity: '1' },
				},
				fadeUp: {
					'0%': { opacity: '0', transform: 'translateY(10px)' },
					'100%': { opacity: '1', transform: 'translateY(0)' },
				},
				slideIn: {
					'0%': { transform: 'translateX(-100%)' },
					'100%': { transform: 'translateX(0)' },
				},
				scaleIn: {
					'0%': { transform: 'scale(0.9)', opacity: '0' },
					'100%': { transform: 'scale(1)', opacity: '1' },
				},
			},
			boxShadow: {
				'soft': 'none',
				'glow': 'none',
				'inner-glow': 'none',
				'warm': 'none',
			},
			backgroundImage: {
				'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
				'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
				'mesh-gradient': 'linear-gradient(to bottom right, var(--tw-gradient-stops))',
				'warm-gradient': 'linear-gradient(135deg, rgba(251, 146, 60, 0.1) 0%, rgba(251, 191, 36, 0.1) 100%)',
			},
		},
	},
	plugins: [require("@tailwindcss/typography"), require("daisyui")],
	daisyui: {
		themes: [
			{
				ink: {
					"primary": "#7C9CFF",
					"primary-content": "#0B0B0D",
					"secondary": "#7C9CFF",
					"secondary-content": "#0B0B0D",
					"accent": "#7C9CFF",
					"accent-content": "#0B0B0D",
					"neutral": "#ECECEF",
					"neutral-content": "#0B0B0D",
					"base-100": "#0B0B0D",
					"base-200": "#131316",
					"base-300": "#24242A",
					"base-content": "#ECECEF",
					"info": "#7C9CFF",
					"success": "#4ADE80",
					"warning": "#FBBF24",
					"error": "#F87171",
					"--rounded-box": "0.75rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "0.375rem",
					"--animation-btn": "0",
					"--animation-input": "0",
					"--btn-focus-scale": "1",
				},
			},
			{
				paper: {
					"primary": "#3451D1",
					"primary-content": "#FFFFFF",
					"secondary": "#3451D1",
					"secondary-content": "#FFFFFF",
					"accent": "#3451D1",
					"accent-content": "#FFFFFF",
					"neutral": "#111114",
					"neutral-content": "#FFFFFF",
					"base-100": "#FAFAFB",
					"base-200": "#FFFFFF",
					"base-300": "#E6E6EB",
					"base-content": "#111114",
					"info": "#3451D1",
					"success": "#15803D",
					"warning": "#B45309",
					"error": "#B91C1C",
					"--rounded-box": "0.75rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "0.375rem",
					"--animation-btn": "0",
					"--animation-input": "0",
					"--btn-focus-scale": "1",
				},
			},
		],
		darkTheme: "ink",
	},
};
